### ISSUE TITLE
Uključivanje blok nastave u raspored

### ISSUE THREAD

**Issue by Luburic** [unsftn/raspored#1]
Pretpostavljam da si svestan problem, al' da ga istaknem.

Po [izveštaju](https://github.com/unsftn/raspored/blob/main/izvestaj/ucionice.txt) ispada da je (na primer) NTP-506 slobodna većinu dana posle 13h. Po [rasporedu RA](http://www.ftn.uns.ac.rs/1011839733/racunarstvo-i-automatika) se vidi od 10. stranice pa na dalje da je učionica zauzeta. Na primer:

    19.10.2022 1 13:00 16:00 NTP-506 lab.vežbe Programska podrška u realnom vremenu 1 Bokan Dejan
    19.10.2022 2 16:15 19:15 NTP-506 lab.vežbe Programska podrška u realnom vremenu 1 Bokan Dejan

Možda bi najjednostavnije rešenje bilo da se identifikuje postojanje učionice u segmentima blok nastave i da se 1 instanca tretira kao da je učionica zauzeta čitav semestar u tom slotu.

**Comment by igordejanovic** [comment]
Ne, nisam znao za problem :)

Parser radi po "best effort" principu jer ulazni pdf-ovi nemaju fiksnu strukturu tako da se prepoznaje šta je definisao gramatikom a sve ostalo se preskače i smatra se delom okolnog teksta. Ovo što si pronašao je novi format zapisa blok nastave koji nisam video ranije (da li je postojao u starim rasporedima?).

Proširiću ovih dana gramatiku da podrži i ovaj format.

BTW, ako primetiš ovakvih stvari javljaj.

**Comment by igordejanovic** [comment]
Prošireno sa podrškom za blok nastavu. Termini blok nastave su sortirani po vremenu pa po datumu tako da je lako uočiti zauzeća.
